# 测试错误处理的HTTP文件

### 测试域名解析错误
GET http://this-domain-does-not-exist-123456789.com/
Accept: application/json

### 测试连接被拒绝错误
GET http://localhost:9999/
Accept: application/json

### 测试超时错误
GET http://httpbin.org/delay/10
Accept: application/json 